services:
  quiz_backend_service:
    image: quiz_backend:latest
    container_name: quiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 5
    volumes:
      - static-data:/usr/src/app/static
      - media-data:/usr/src/app/media
    env_file:
      - .prod.env
    networks:
      - quizNetwork

  quiz_celery_service:
    image: quiz_backend:latest
    container_name: quiz_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - static-data:/usr/src/app/static
      - media-data:/usr/src/app/media
    env_file:
      - .prod.env
    networks:
      - quizNetwork

  quiz_daphne_service:
    image: quiz_backend:latest
    container_name: quiz_daphne
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - static-data:/usr/src/app/static
      - media-data:/usr/src/app/media
    env_file:
      - .prod.env
    networks:
      - quizNetwork

volumes:
  static-data:
  media-data:

networks:
  quizNetwork:
    external: true
