# Generated by Django 4.2.7 on 2023-11-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['points'], 'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
    ]
