# Generated by Django 4.2.7 on 2024-12-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='for_test',
            field=models.BooleanField(default=False),
        ),
    ]
